### ISSUE TITLE
Gateway Timeout - Impossible to Access Akeneo Connector Menu

### ISSUE THREAD

**Issue by vbidou** [akeneo/magento2-connector-community#14] opened 2019-08-15 20:45 UTC
Hello,
I Installed the connector this afternoon.
At the beginning it was working well and I could access the Akeneo Connector Menu in the Catalog of the Configuration.
Then, each time I accessed it, the query was getting longer and longer (was longer to reach it).
Until when finally, I couldn't reach it anymore (Gateway Timeout).
Now it's no longer possible to access the Akeneo Connector from M2.
The rest of M2 menus are working well and are instantly accessible.
Also, I haven't performed any change neither on M2, nor on my Server.

I suspect a problem with the Cron, but maybe I am wrong.
What do you think can be done to recover the access ?

Thanks for your advice.

**Comment by Dnd-Gimix** [comment] 2019-08-22 10:08
Hello @vbidou ,

Thank you for your interest in Akeneo Connector.

In the configuration page, the connector is fetching data from API calls to fill different configuration options.
It seems in your case that those calls are taking too much time or that they are not able to contact your Akeneo instance.

Can you confirm that your Akeneo instance and your Magento instance can communicate correctly ?

I don't think that this issue is caused by CRON task, Akeneo Connector doesn't have any of them declared natively.

Thank you.

Regards,

**Comment by vbidou** [comment] 2019-08-22 19:46
Hello,
Indeed I have a problem on the connection to my Akeneo instance.
I need to search a freelancer to help me with my server configuration.
My Akeneo is served through a Bitnami Stack installed on a Virtual Server (Oracle VM VirtualBox) who is located on my local server. I wasn't able to resolve the configuration of the Virtual Host of my Bitnami stack.

In summary, I can reach my Akeneo PIM with an IP / Port adress like (exemple) http://88.158.48.63:8888 but not with a normal URL address like pim.technostok.com
Therefore, the connector doesn't accept the IP address that I provide.

I need to find a way to configure my Bitnami VirtualHost. I spent 5 days on this, looking and applying all Bitnami, Akeneo, an Apache documentation related to VirtualHost but couldn't find the trick. If someone in this community has experience with such, I am ready to take some advises and hire the time spent to resolve it.

I will inform here if I manage to resolve this problem (and provide all needful details).

**Comment by vbidou** [comment] 2019-08-22 19:55
Hello,
Indeed I have a problem on the connection to my Akeneo instance.
I need to search a freelancer to help me with my server configuration.
My Akeneo is served through a Bitnami Stack installed on a Virtual Server (Oracle VM VirtualBox) who is located on my local server. I wasn't able to resolve the configuration of the Virtual Host of my Bitnami stack.
In summary, I can reach for myself (outside of connector) my Akeneo PIM with an IP / Port adress like (exemple) http://88.158.48.63:8888 but not with a normal URL address like pim.technostok.com
Therefore, the connector doesn't accept the IP address that I provide and freeze.

I need to find a way to configure my Bitnami VirtualHost. 
I spent 5 days on this, looking and applying all Bitnami, Akeneo, an Apache documentation related to VirtualHost but couldn't find the trick. If someone in this community has experience with such, I am ready to take some advises and hire the time spent to resolve it.
I will inform here if I manage to resolve this problem (and provide all needful details).

**Comment by Dnd-Gimix** [comment] 2019-10-02 15:21
Hello @vbidou ,

Did you managed to solve your connection problem ?

Regards,

**Comment by vbidou** [comment] 2019-10-02 16:28
Dear Dnd Team,
No I wasn't able to resolve my problem. 
Hence I concluded IP Adressing is the wrong methodology and that I need to setup my PIM with a VirtualHost, and currently I am still working to redeploy my Akeneo. I will reattempt to use the connector once I perform this task. We can close this topic and in case I am unsuccessful, with the same related issue, then I will reopen the case.
Thank you 👍

**Comment by Dnd-Gimix** [comment] 2019-10-02 16:30
@vbidou ,

Thank you for your feedback, hope you figure it out !

I'll close the issue.
Have a good day.

Regards,

**Closed by Dnd-Gimix** 2019-10-02 16:30 UTC

**Comment by vbidou** [comment] 2019-11-23 10:33
For info: I just reopen the issue with a different ticket, which is more explicit since the very beginning.
