### ISSUE TITLE
Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in line 97

### ISSUE THREAD

**Issue by wvanderlaan** [akeneo/magento2-connector-community#229] opened 2020-06-29 10:34 UTC
Scope: 
Magento2 CE 2.3.5-p1
Akeneo connector CE 100.4.9

We  installed the akeneo-magento-connector using following instructions:
https://help.akeneo.com/magento2-connector/v100/articles/download-connector.html
Install "Akeneo Connector for Magento 2 Community Edition"

Then using instruction to verify if the connector configuration is available:
https://help.akeneo.com/magento2-connector/v100/articles/01-where-configuration.html

When selecting (clicking on) the "Akeneo Connector" under Stores --> Configuration --> Catalog, we get an exception.

1 exception(s):
Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /srv/magento/vendor/akeneo/module-magento2-connector-community/Model/Source/Filters/Family.php on line 97

Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /srv/magento/vendor/akeneo/module-magento2-connector-community/Model/Source/Filters/Family.php on line 97

Complete dump:
[Akeneo_Connector_Exception.txt](https://github.com/akeneo/magento2-connector-community/files/4844919/Akeneo_Connector_Exception.txt)

**Comment by franckcharpentier** [comment] 2020-07-02 15:29
Same issue with the same versions.

**Comment by Dnd-Gimix** [comment] 2020-07-07 14:04
Hello @franckcharpentier @wvanderlaan ,

Thank you for your interest in Akeneo Connector for Magento 2.

We have provided a fix for this issue in the latest 100.4.10 version of the connector.
Could you please update and come back to us to confirm that it solved your issue ?Many thanks.

Regards,

**Comment by wvanderlaan** [comment] 2020-07-07 14:14
Dear DnD-Gimix,

I installed version 100.4.10.

The page is now displaying.

Best regards,

Wim

**Comment by Dnd-Gimix** [comment] 2020-07-07 14:15
@wvanderlaan ,

Great, thank you very much for your quick feedback.

I'll close this issue and wish you a good day !

Regards,

**Comment by wvanderlaan** [comment] 2020-07-07 14:18
@Dnd-Gimix ,

Thank you for solving.

Regards,

**Comment by yutv** [comment] 2020-07-15 08:22
@Dnd-Gimix the issue is resolved so please close the Github issue.

**Closed** 2020-07-15 08:25 UTC
